apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "screensnap.fullname" . }}
  labels:
    {{- include "screensnap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "screensnap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "screensnap.selectorLabels" . | nindent 8 }}
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "true"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "screensnap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.appVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            periodSeconds: 45
            httpGet:
              path: /__health
              port: http
          readinessProbe:
            periodSeconds: 20
            httpGet:
              path: /__health
              port: http
          env:
            - name: upstream_base
              value: {{ .Values.upstream_base }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
