{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "screensnap.serviceAccountName" . }}
  labels:
{{ include "screensnap.labels" . | nindent 4 }}
{{- end -}}
