#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: harbor.ntppool.org/ntppool/archiver
  # -- image tag, defaults to appVersion
  #tag:
  # -- image pull policy
  #pullPolicy: IfNotPresent
  pullPolicy: Always

# -- environment variables. See more environment variables in the [monitor-api documentation](https://go.ntppool.org/monitor/cmd/monitor-api).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

podLabels: {}

command:
#  - /bin/zsh
  - /archiver/archive-continuously

args:
#  - archive
#  - -c
#  - "sleep 86400"

env:
  wait: 120

service:
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  {}
  # data:
  #   enabled: false
  #   mountPath: /data


controller:
  strategy: Recreate
#  strategy: RollingUpdate

resources:
  limits:
    cpu: 2
    memory: 3Gi
  requests:
    cpu: 500m
    memory: 256Mi
