apiVersion: v2
name: smtp
description: exim based smtp smarthost / mail relay
home: https://gitlab.com/egos-tech/smtp
type: application

# This is the chart version. This version number should be
# incremented each time you make changes
# to the chart and its templates, including the app version.
version: 2.1.3

# This is the version number of the application being deployed.
appVersion: 1.0.1

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Support numeric configuration settings via --set parameters"
