{{- if .Values.jobs.global.enabled -}}

{{- $chart_name := include "ntppool.fullname" . }}
{{- $labels := include "ntppool.labels" . -}}
{{- $containerDefaults := include "ntppool.appContainerDefaults" . -}}
{{- $volumes := include "ntppool.appVolumes" . -}}
{{- $root   := . -}}
{{- $values := .Values -}}
{{- $jobGlobalValues := .Values.jobs.global -}}

{{- range $name, $job := .Values.jobs }}
{{- if and (ne $name "global") ($job.enabled) }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $chart_name }}-{{ $name }}"
  labels:
    {{- $labels | nindent 4 }}
spec:
  concurrencyPolicy: {{ if $job.concurrencyPolicy }}{{ $job.concurrencyPolicy }}{{ else }}Replace{{ end }}
  failedJobsHistoryLimit: {{ if $job.failedJobsHistoryLimit }}{{ $job.failedJobsHistoryLimit }}{{ else }}2{{end}}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- $labels | nindent 12 }}
            cron: {{ $name }}
          annotations:
          {{- with $values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $jobGlobalValues.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          activeDeadlineSeconds: 1800
          serviceAccountName: {{ include "ntppool.serviceAccountName" $root }}
          securityContext:
            {{ toYaml $values.podSecurityContext | nindent 12 }}
          {{- with $values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          {{ range $c := $job.containers }}
          - name: {{ default $name $c.name }}
            {{- $containerDefaults | nindent 12 }}
            {{ if $c.command }}
            command:
              {{- toYaml . | nindent 14 }}
            {{ else }}
            command:
              - /ntppool/docker/entrypoint
            {{ end }}
            {{- with $c.args }}
            args:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            resources:
              {{- toYaml $values.resources_low | nindent 14 }}
          {{ end }}
          securityContext:
            {{ toYaml $values.podSecurityContext | nindent 12 }}

          restartPolicy: Never
          volumes:
            {{ $volumes | nindent 10 }}
  schedule: {{ $job.schedule | quote }}
  startingDeadlineSeconds: 172400
  successfulJobsHistoryLimit: 2
{{- end }}
{{- end -}}
{{- end -}}
