{{ if .Values.ingress.enabled -}}

{{ $g := . }}
{{ $values := $g.Values }}
{{ $config := .Values.config -}}

{{ $fullName := include "ntppool.fullname" . -}}

{{ range $ingress_type := .Values.ingress.types -}}
---
{{ $svcPort := $values.service.port -}}
apiVersion: networking.k8s.io/v1
{{ $hosts := "" }}
{{ if eq $ingress_type "manage" }}
{{   $hosts = splitList "," $config.manage_hostname }}
{{ else }}
{{   $hosts = splitList "," $config.web_hostname }}
{{ end }}
{{ $tls := false }}
{{ if eq $ingress_type "manage" }}
{{   $tls = eq $config.manage_tls "yes" }}
{{ else }}
{{   $tls = eq $config.web_tls "yes" }}
{{ end }}

{{ $dataAPI  := index $values "data-api" -}}
{{ $dataAPIService := printf "%s-%s" $fullName "-data-api" -}}
{{ if ne $dataAPI.serviceName "" -}}
{{   $dataAPIService = $dataAPI.serviceName -}}
{{ end -}}

kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $ingress_type }}
  labels:
    {{ include "ntppool.labels" $g | nindent 4 }}
    type: {{ $ingress_type }}
  annotations:
    {{- if $tls }}
    kubernetes.io/tls-acme: "true"
    {{ end }}
    {{ if eq $ingress_type "data-api" }}
    haproxy-ingress.github.io/rewrite-target: /api
    {{ end }}

  {{ with $values.ingress.annotations }}
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
{{- if $values.ingress.class }}
  ingressClassName: {{ $values.ingress.class }}
{{- end }}
{{ if $tls }}
  tls:
    - hosts:
      {{ range $hosts }}
        - {{ . | quote }}
      {{ end }}
      secretName: {{ $fullName }}-{{ $ingress_type }}-tls
{{ end }}
  rules:
  {{ range $idx, $h := $hosts }}
    - host: {{ $h | quote }}
      http:
        paths:
      {{ if eq $ingress_type "data-api" }}
          - path: /api/data
            pathType: Prefix
            backend:
              service:
                name: {{ $dataAPIService }}
                port:
                  number: {{ $svcPort }}
      {{ else }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{ if eq $ingress_type "web" }}
          - path: /graph/
            pathType: Prefix
            backend:
              service:
                name: {{ $dataAPIService }}
                port:
                  number: 80
          {{ end }}
      {{ end }}
  {{ end }}
{{ end }}
{{ end }}
